# Generated by Django 5.0.7 on 2025-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_peritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome_perito', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tbl_peritos',
            },
        ),
        migrations.CreateModel(
            name='tbl_salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(blank=True, max_length=25, null=True)),
                ('perito', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'tbl_salas',
            },
        ),
        migrations.CreateModel(
            name='tbl_unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsecao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_unidades',
            },
        ),
        migrations.CreateModel(
            name='tbl_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=128)),
                ('unidade', models.CharField(blank=True, max_length=3, null=True)),
                ('perito', models.BooleanField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tbl_usuarios',
            },
        ),
        migrations.CreateModel(
            name='tbl_pericias_agendadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pericia', models.CharField(blank=True, max_length=20, null=True)),
                ('jurisdicao', models.CharField(blank=True, max_length=100, null=True)),
                ('perito', models.CharField(blank=True, max_length=100, null=True)),
                ('periciado', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_parte', models.CharField(blank=True, max_length=14, null=True)),
                ('processo', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao_pericia', models.CharField(blank=True, max_length=100, null=True)),
                ('compareceu_pericia', models.BooleanField(default=False)),
                ('hora_entrada', models.TimeField()),
                ('hora_saida', models.TimeField()),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('data_marcada', models.DateField(blank=True, null=True)),
                ('hora_marcada', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_pericias_agendadas',
                'indexes': [models.Index(fields=['periciado', 'processo', 'data_pericia', 'situacao_pericia'], name='tbl_pericia_pericia_4d5c9a_idx')],
                'unique_together': {('periciado', 'processo', 'data_pericia', 'situacao_pericia')},
            },
        ),
    ]
